server:
  port: 8080
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:burhan.jks
    key-store-type: JKS
    key-password: 123456
    key-store-password: 123456

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/articledb
    username: postgres
    password: postgres
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:./
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet